# Generated by Django 5.2.8 on 2025-11-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_display_order_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_note', models.TextField(blank=True)),
            ],
        ),
    ]
