# Generated by Django 5.2.8 on 2025-11-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('display_order', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for MAIN categories. Set a parent to make this a SUB category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Percentage discount (0–100). 0 means no discount.'),
        ),
    ]
