# Generated by Django 5.2.8 on 2025-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this final price overrides the percentage discount.', max_digits=10, null=True),
        ),
    ]
