# Generated by Django 5.2.8 on 2025-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
