# Generated by Django 5.2.8 on 2025-12-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_printed_order_printed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Minimum order amount in TL', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount Tier',
                'verbose_name_plural': 'Discount Tiers',
                'ordering': ['threshold'],
            },
        ),
    ]
