# Generated by Django 5.2.8 on 2025-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_discounttier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounttier',
            options={'ordering': ['customer_type', 'threshold'], 'verbose_name': 'Discount Tier', 'verbose_name_plural': 'Discount Tiers'},
        ),
        migrations.AddField(
            model_name='discounttier',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Perakende'), ('wholesale', 'Toptan')], default='retail', help_text='Customer type this discount applies to', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Perakende'), ('wholesale', 'Toptan')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
