# Generated by Django 5.2.8 on 2025-12-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_discounttier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, default='#CCCCCC', help_text='Hex color code for subcategory bar (e.g., #FF0000 for red)', max_length=7),
        ),
    ]
