# Generated by Django 5.2.8 on 2026-01-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Red Shimmer', 'Rainbow Gradient', 'Ocean Blues'", max_length=100)),
                ('colors', models.JSONField(default=list, help_text='Array of hex colors: ["#FF0000", "#FFFF00", "#00FF00"]')),
                ('effect_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient-light', 'Light Gradient (20% opacity)'), ('gradient-medium', 'Medium Gradient (40% opacity)'), ('gradient-strong', 'Strong Gradient (80% opacity)'), ('shimmer', 'Shimmer/Glitter Effect'), ('linear', 'Linear Multi-color')], default='gradient-medium', help_text='Visual effect to apply', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_code',
        ),
        migrations.AddField(
            model_name='category',
            name='color_palette',
            field=models.ForeignKey(blank=True, help_text='Color scheme for this subcategory bar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.colorpalette'),
        ),
    ]
